version: '3'

networks:
  laravel:

services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - user=${user:-achawayne}
        - UID=${UID:-1000}
        - GID=${GID:-1000}

    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html:delegated
    #   - ./storage:/var/www/storage
    env_file:
      - path: ./.env
    environment:
      RABBITMQ_HOST: rattlesnake-01.rmq.cloudamqp.com
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: xsmlgpag
      RABBITMQ_PASSWORD: GTwTKX8CNerXVpzKyByjGUbAz32Qqz-e
      RABBITMQ_VHOST: xsmlgpag



    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - user=${user:-achawayne}
        - UID=${UID:-1000}
        - GID=${GID:-1000}

    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - laravel

  composer:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - user=${user:-achawayne}
        - UID=${UID:-1000}
        - GID=${GID:-1000}

    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    command: sh -c "composer install --ignore-platform-reqs && php artisan key:generate"
    networks:
      - laravel




  npm:
    image: node:current-alpine
    volumes:
      - ./:/var/www/html

    ports:
      - "3003:3000"
      - "3004:3001"
      - "5175:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - laravel


  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - user=${user:-achawayne}
        - UID=${UID:-1000}
        - GID=${GID:-1000}


    volumes:
      - ./:/var/www/html:delegated

    entrypoint: [ 'php', '/var/www/html/artisan', 'queue:listen']

    networks:
      - laravel



