version: '3'

networks:
  basketNotification:

services:

  notification:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile

    ports:
      - "8002:80"
    volumes:
      - ./:/var/www/html:delegated
    env_file:
      - path: ./.env
    environment:
      RABBITMQ_HOST: rattlesnake-01.rmq.cloudamqp.com
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: xsmlgpag
      RABBITMQ_PASSWORD: GTwTKX8CNerXVpzKyByjGUbAz32Qqz-e
      RABBITMQ_VHOST: xsmlgpag
    depends_on:
      - php
    networks:
      - basketNotification


  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile

    ports:
      - "9001:9000"
    volumes:
      - ./:/var/www/html:delegated

    networks:
      - basketNotification


  composer:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile

    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - basketNotification

  npm:
    image: node:current-alpine
    volumes:
      - ./:/var/www/html

    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - basketNotification




  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile

    volumes:
      - ./:/var/www/html:delegated
    entrypoint: [ 'php', '/var/www/html/artisan', 'queue:listen']

    networks:
      - basketNotification


